In [49]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
#from sklearn.feature_extraction.text import TfidfVectorizer
#NLTK-------------------------------
import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize
from nltk.stem.snowball import SnowballStemmer
from nltk.corpus import stopwords
#from nltk.stemporter import PorterStemmer
# Import libraries for feature 
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix,classification_report
from sklearn import metrics
import warnings
warnings.filterwarnings("ignore")
from google.colab import drive
drive.mount('/gdrive')
#Change current working directory to gdrive
%cd /gdrive


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive


In [50]:
#Read files
textfile = r'/gdrive/My Drive/508-A5/Comments.csv'
textData = pd.read_csv(textfile) #creates a dataframe

CustInfofile = r'/gdrive/My Drive/508-A5/Customers.csv'
CustInfoData = pd.read_csv(CustInfofile)  #creates a dataframe

print(textData.shape)
print(CustInfoData.shape)


(2070, 2)
(2070, 17)


In [51]:
#Extract target column from Customer Info file
y_train = CustInfoData["TARGET"]
X_train = CustInfoData.drop(columns=["TARGET"]) #extracting training data without the target column
                     
print(X_train.shape)
print(textData.shape)
textData.head()
print(y_train)

(2070, 16)
(2070, 2)
0       Cancelled
1         Current
2         Current
3         Current
4       Cancelled
          ...    
2065    Cancelled
2066    Cancelled
2067    Cancelled
2068    Cancelled
2069    Cancelled
Name: TARGET, Length: 2070, dtype: object


In [0]:
#Tokenize - Split the sentences to lists of words
textData['CommentsTokenized'] = textData['Comments'].apply(word_tokenize)

export_csv = textData.to_csv(r'/gdrive/My Drive/508-A5/TextDataTokenized1.csv')


In [0]:
# Use English stemmer.
from nltk.stem import PorterStemmer
from nltk.stem import LancasterStemmer
stemmer = PorterStemmer()

#Now do stemming - create a new dataframe to store stemmed version
newTextData=pd.DataFrame()
newTextData=textData.drop(columns=["CommentsTokenized","Comments"])
newTextData['CommentsTokenizedStemmed'] = textData['CommentsTokenized'].apply(lambda x: [stemmer.stem(y) for y in x]) # Stem every word.

#export_csv = newTextData.to_csv(r'/gdrive/My Drive/508-A5/newTextDataTS-PP.csv')

#Join stemmed strings
newTextData['CommentsTokenizedStemmed'] = newTextData['CommentsTokenizedStemmed'].apply(lambda x: " ".join(x))

#export_csv = newTextData.to_csv(r'/gdrive/My Drive/508-A5/newTextData-Joined-PP.csv')


In [54]:
#Do Bag-Of-Words model - Term - Document Matrix
#Learn the vocabulary dictionary and return term-document matrix.
#count_vect = CountVectorizer(stop_words=None)
count_vect = CountVectorizer(stop_words='english',lowercase=False)
TD_counts = count_vect.fit_transform(newTextData.CommentsTokenizedStemmed)
print(TD_counts.shape)
TD_counts.dtype
print(count_vect.get_feature_names())
#print(TD_counts)
DF_TD_Counts=pd.DataFrame(TD_counts.toarray())
#print(DF_TD_Counts)
#export_csv = DF_TD_Counts.to_csv(r'/gdrive/My Drive/508-A5/TD_counts-TokenizedStemmed.csv')

(2070, 366)
['3399', '3g', 'As', 'CC', 'He', 'If', 'In', 'Is', 'It', 'We', 'abysm', 'access', 'accessori', 'adapt', 'add', 'addit', 'additon', 'address', 'adit', 'adress', 'advertis', 'afraid', 'alway', 'angel', 'angri', 'ani', 'anoth', 'anyth', 'anytim', 'area', 'asap', 'ask', 'bad', 'basic', 'bateri', 'batteri', 'becaus', 'believ', 'better', 'bigger', 'book', 'bought', 'brain', 'bring', 'built', 'busi', 'button', 'buy', 'cancel', 'cancer', 'car', 'care', 'carrier', 'caus', 'cc', 'cell', 'certain', 'chang', 'charg', 'charger', 'check', 'chip', 'citi', 'claim', 'cleariti', 'cold', 'comapr', 'compani', 'compar', 'competit', 'complain', 'complaint', 'concept', 'connect', 'consisit', 'consist', 'constanli', 'contact', 'continu', 'contract', 'correct', 'cost', 'coupl', 'cover', 'coverag', 'creat', 'credit', 'cstmer', 'cstmr', 'current', 'cust', 'custom', 'customr', 'date', 'day', 'dead', 'decent', 'defect', 'deo', 'did', 'die', 'differ', 'difficult', 'digiti', 'direct', 'disabl', 'doe', 'd

In [0]:
# Use English stemmer.
stemmer = LancasterStemmer()

#Now do stemming - create a new dataframe to store stemmed version
newTextData=pd.DataFrame()
newTextData=textData.drop(columns=["CommentsTokenized","Comments"])
newTextData['CommentsTokenizedStemmed'] = textData['CommentsTokenized'].apply(lambda x: [stemmer.stem(y) for y in x]) # Stem every word.

#export_csv = newTextData.to_csv(r'/gdrive/My Drive/508-A5/newTextDataTS-PP.csv')

#Join stemmed strings
newTextData['CommentsTokenizedStemmed'] = newTextData['CommentsTokenizedStemmed'].apply(lambda x: " ".join(x))

#export_csv = newTextData.to_csv(r'/gdrive/My Drive/508-A5/newTextData-Joined-PP.csv')

In [56]:
#Do Bag-Of-Words model - Term - Document Matrix
#Learn the vocabulary dictionary and return term-document matrix.
#count_vect = CountVectorizer(stop_words=None)
count_vect = CountVectorizer(stop_words='english',lowercase=False)
TD_counts = count_vect.fit_transform(newTextData.CommentsTokenizedStemmed)
print(TD_counts.shape)
TD_counts.dtype
print(count_vect.get_feature_names())
#print(TD_counts)
DF_TD_Counts=pd.DataFrame(TD_counts.toarray())
#print(DF_TD_Counts)
#export_csv = DF_TD_Counts.to_csv(r'/gdrive/My Drive/508-A5/TD_counts-TokenizedStemmed.csv')

(2070, 364)
['3399', '3g', 'abysm', 'access', 'ad', 'adapt', 'addit', 'additon', 'address', 'adit', 'adress', 'advert', 'afraid', 'aft', 'al', 'alway', 'angel', 'angry', 'anoth', 'anyth', 'anytim', 'ar', 'asap', 'ask', 'bad', 'bas', 'batery', 'battery', 'becaus', 'believ', 'bet', 'big', 'bil', 'book', 'bought', 'brain', 'bring', 'built', 'busy', 'button', 'buy', 'cal', 'cancel', 'car', 'carry', 'caus', 'cc', 'cel', 'certain', 'chang', 'charg', 'check', 'chip', 'city', 'claim', 'clear', 'cold', 'comapr', 'comp', 'company', 'competit', 'complain', 'complaint', 'conceiv', 'connect', 'consisit', 'consist', 'const', 'contact', 'continu', 'contract', 'correct', 'cost', 'coupl', 'cov', 'cre', 'credit', 'cstmer', 'cstmr', 'cur', 'cust', 'custom', 'customr', 'dat', 'day', 'dead', 'dec', 'defect', 'deo', 'did', 'die', 'diff', 'difficult', 'digit', 'direct', 'dis', 'doe', 'don', 'dont', 'drop', 'dur', 'dying', 'easy', 'effect', 'encount', 'end', 'enemy', 'equip', 'ev', 'everytim', 'everywh', 'evr

In [0]:
# Use English stemmer.
stemmer = SnowballStemmer("english")

#Now do stemming - create a new dataframe to store stemmed version
newTextData=pd.DataFrame()
newTextData=textData.drop(columns=["CommentsTokenized","Comments"])
newTextData['CommentsTokenizedStemmed'] = textData['CommentsTokenized'].apply(lambda x: [stemmer.stem(y) for y in x]) # Stem every word.

export_csv = newTextData.to_csv(r'/gdrive/My Drive/508-A5/newTextDataTS.csv')

#Join stemmed strings
newTextData['CommentsTokenizedStemmed'] = newTextData['CommentsTokenizedStemmed'].apply(lambda x: " ".join(x))

export_csv = newTextData.to_csv(r'/gdrive/My Drive/508-A5/newTextData-Joined.csv')

In [58]:
#Do Bag-Of-Words model - Term - Document Matrix
#Learn the vocabulary dictionary and return term-document matrix.
#count_vect = CountVectorizer(stop_words=None)
count_vect = CountVectorizer(stop_words='english',lowercase=False)
TD_counts = count_vect.fit_transform(newTextData.CommentsTokenizedStemmed)
print(TD_counts.shape)
TD_counts.dtype
print(count_vect.get_feature_names())
#print(TD_counts)
DF_TD_Counts=pd.DataFrame(TD_counts.toarray())
#print(DF_TD_Counts)
export_csv = DF_TD_Counts.to_csv(r'/gdrive/My Drive/508-A5/TD_counts-TokenizedStemmed.csv')

(2070, 354)
['3399', '3g', 'abysm', 'access', 'accessori', 'adapt', 'add', 'addit', 'additon', 'address', 'adit', 'adress', 'advertis', 'afraid', 'alway', 'angel', 'angri', 'ani', 'anoth', 'anyth', 'anytim', 'area', 'asap', 'ask', 'bad', 'basic', 'bateri', 'batteri', 'becaus', 'believ', 'better', 'bigger', 'book', 'bought', 'brain', 'bring', 'built', 'busi', 'button', 'buy', 'cancel', 'cancer', 'car', 'care', 'carrier', 'caus', 'cc', 'cell', 'certain', 'chang', 'charg', 'charger', 'check', 'chip', 'citi', 'claim', 'cleariti', 'cold', 'comapr', 'compani', 'compar', 'competit', 'complain', 'complaint', 'concept', 'connect', 'consisit', 'consist', 'constan', 'contact', 'continu', 'contract', 'correct', 'cost', 'coupl', 'cover', 'coverag', 'creat', 'credit', 'cstmer', 'cstmr', 'current', 'cust', 'custom', 'customr', 'date', 'day', 'dead', 'decent', 'defect', 'deo', 'did', 'die', 'differ', 'difficult', 'digiti', 'direct', 'disabl', 'doe', 'don', 'dont', 'drop', 'dure', 'easier', 'effect', '

In [59]:
#Compute TF-IDF Matrix
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(TD_counts)
print(X_train_tfidf.shape)
DF_TF_IDF=pd.DataFrame(X_train_tfidf.toarray())
print(DF_TF_IDF)
export_csv= DF_TF_IDF.to_csv(r'/gdrive/My Drive/508-A5/TFIDF_counts-TokenizedStemmed.csv')


(2070, 354)
      0    1    2    3    4    5    6    ...       347  348  349  350  351  352  353
0     0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.000000  0.0  0.0  0.0  0.0  0.0  0.0
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.000000  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.000000  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.000000  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.000000  0.0  0.0  0.0  0.0  0.0  0.0
...   ...  ...  ...  ...  ...  ...  ...  ...       ...  ...  ...  ...  ...  ...  ...
2065  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.356121  0.0  0.0  0.0  0.0  0.0  0.0
2066  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.356121  0.0  0.0  0.0  0.0  0.0  0.0
2067  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.356121  0.0  0.0  0.0  0.0  0.0  0.0
2068  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.356121  0.0  0.0  0.0  0.0  0.0  0.0
2069  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.35612

In [0]:
#List of Categorical Features
categoricalFeatures = ["ID", 	'Sex', 	'Status',	'Children',	"Est_Income", 	"Car_Owner", 	"Usage", 	'Age', 	"RatePlan", 	"LongDistance", 	
                       "International", 	"Local", 	"Dropped", 	"Paymethod", 	"LocalBilltype", 	"LongDistanceBilltype"]

In [73]:
#Combine Train and test for one Hot Encoding
combined_Data = pd.concat([X_train, DF_TF_IDF], axis = 1)

#Do one Hot encoding for categorical features for combined data
combined_data = pd.get_dummies(combined_Data,columns=categoricalFeatures)

print("combined_data",combined_data.shape)


combined_data (2070, 4136)


In [82]:
#Feature selection Filter
new_DF_TF_IDF = SelectKBest(score_func=chi2, k=50).fit_transform(combined_data,y_train)
new_DF_TF_IDF.shape

DF_TF_IDF_SelectedFeatures= pd.DataFrame(new_DF_TF_IDF)
print(DF_TF_IDF_SelectedFeatures)

export_csv= DF_TF_IDF_SelectedFeatures.to_csv(r'/gdrive/My Drive/508-A5/TFIDF_counts-Selected Features.csv')


       0         1    2    3    4        5   ...   44   45   46   47   48   49
0     0.0  0.000000  0.0  0.0  0.0  0.00000  ...  0.0  0.0  0.0  0.0  0.0  1.0
1     0.0  0.000000  0.0  0.0  0.0  0.37653  ...  0.0  0.0  0.0  0.0  0.0  0.0
2     0.0  0.000000  0.0  0.0  0.0  0.37653  ...  0.0  0.0  0.0  0.0  0.0  0.0
3     0.0  0.000000  0.0  0.0  0.0  0.37653  ...  0.0  0.0  0.0  0.0  0.0  0.0
4     0.0  0.000000  0.0  0.0  0.0  0.37653  ...  0.0  0.0  0.0  0.0  0.0  0.0
...   ...       ...  ...  ...  ...      ...  ...  ...  ...  ...  ...  ...  ...
2065  0.0  0.466708  0.0  0.0  0.0  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0
2066  0.0  0.466708  0.0  0.0  0.0  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0
2067  0.0  0.466708  0.0  0.0  0.0  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0
2068  0.0  0.466708  0.0  0.0  0.0  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0
2069  0.0  0.466708  0.0  0.0  0.0  0.00000  ...  0.0  0.0  0.0  0.0  0.0  0.0

[2070 rows x 50 columns]


In [83]:
#Construct a Random Forest Classifier on text data
clf=RandomForestClassifier()
RF_text = clf.fit(DF_TF_IDF_SelectedFeatures,y_train)
print("Accuracy score (training): {0:.6f}".format(clf.score(DF_TF_IDF_SelectedFeatures, y_train)))
rf_predictions = clf.predict(DF_TF_IDF_SelectedFeatures)
print("Confusion Matrix:")
print(confusion_matrix(y_train, rf_predictions))
print("Classification Report")
print(classification_report(y_train, rf_predictions))

Accuracy score (training): 0.828502
Confusion Matrix:
[[ 696  108]
 [ 247 1019]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.74      0.87      0.80       804
     Current       0.90      0.80      0.85      1266

    accuracy                           0.83      2070
   macro avg       0.82      0.84      0.82      2070
weighted avg       0.84      0.83      0.83      2070



In [84]:
#Construct a Decision Tree Classifier on text data
clf=DecisionTreeClassifier()
RF_text = clf.fit(DF_TF_IDF_SelectedFeatures,y_train)
print("Accuracy score (training): {0:.6f}".format(clf.score(DF_TF_IDF_SelectedFeatures, y_train)))
rf_predictions = clf.predict(DF_TF_IDF_SelectedFeatures)
print("Confusion Matrix:")
print(confusion_matrix(y_train, rf_predictions))
print("Classification Report")
print(classification_report(y_train, rf_predictions))

Accuracy score (training): 0.828986
Confusion Matrix:
[[ 697  107]
 [ 247 1019]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.74      0.87      0.80       804
     Current       0.90      0.80      0.85      1266

    accuracy                           0.83      2070
   macro avg       0.82      0.84      0.82      2070
weighted avg       0.84      0.83      0.83      2070



In [79]:
#Merge files

print(CustInfoData.shape)
X_train = CustInfoData.drop(columns=["TARGET"]) #extracting training data without the target column
print(X_train.shape)
combined=pd.concat([X_train, DF_TF_IDF_SelectedFeatures], axis=1)
print(combined.shape)
print(combined)
export_csv= combined.to_csv(r'/gdrive/My Drive/508-A5/Combined-Cust+TFIDF+SelectedFeatures.csv')



(2070, 17)
(2070, 16)
(2070, 66)
        ID Sex Status  Children  Est_Income  ...   45   46   47   48   49
0        1   F      S         1    38000.00  ...  0.0  0.0  0.0  0.0  1.0
1        6   M      M         2    29616.00  ...  0.0  0.0  0.0  0.0  0.0
2        8   M      M         0    19732.80  ...  0.0  0.0  0.0  0.0  0.0
3       11   M      S         2       96.33  ...  0.0  0.0  0.0  0.0  0.0
4       14   F      M         2    52004.80  ...  0.0  0.0  0.0  0.0  0.0
...    ...  ..    ...       ...         ...  ...  ...  ...  ...  ...  ...
2065  3821   F      S         0    78851.30  ...  0.0  0.0  0.0  0.0  0.0
2066  3822   F      S         1    17540.70  ...  0.0  0.0  0.0  0.0  0.0
2067  3823   F      M         0    83891.90  ...  0.0  0.0  0.0  0.0  0.0
2068  3824   F      M         2    28220.80  ...  0.0  0.0  0.0  0.0  0.0
2069  3825   F      S         0    28589.10  ...  0.0  0.0  0.0  0.0  0.0

[2070 rows x 66 columns]


In [85]:
#Feature selection Filter
new_DF_TF_IDF = SelectKBest(score_func=chi2, k=1000).fit_transform(combined_data,y_train)
new_DF_TF_IDF.shape

DF_TF_IDF_SelectedFeatures= pd.DataFrame(new_DF_TF_IDF)
print(DF_TF_IDF_SelectedFeatures)

export_csv= DF_TF_IDF_SelectedFeatures.to_csv(r'/gdrive/My Drive/508-A5/TFIDF_counts-Selected Features.csv')

      0    1    2    3         4         5    ...  994  995  996  997  998  999
0     0.0  0.0  0.0  0.0  0.000000  0.000000  ...  0.0  0.0  0.0  1.0  1.0  0.0
1     0.0  0.0  0.0  0.0  0.000000  0.000000  ...  0.0  0.0  0.0  0.0  0.0  1.0
2     0.0  0.0  0.0  0.0  0.000000  0.000000  ...  0.0  0.0  0.0  1.0  0.0  1.0
3     0.0  0.0  0.0  0.0  0.000000  0.000000  ...  0.0  0.0  0.0  1.0  0.0  1.0
4     0.0  0.0  0.0  0.0  0.000000  0.000000  ...  0.0  0.0  0.0  0.0  1.0  0.0
...   ...  ...  ...  ...       ...       ...  ...  ...  ...  ...  ...  ...  ...
2065  0.0  0.0  0.0  0.0  0.466708  0.443664  ...  0.0  0.0  0.0  1.0  0.0  1.0
2066  0.0  0.0  0.0  0.0  0.466708  0.443664  ...  0.0  0.0  1.0  0.0  0.0  1.0
2067  0.0  0.0  0.0  0.0  0.466708  0.443664  ...  0.0  0.0  0.0  0.0  0.0  1.0
2068  0.0  0.0  0.0  0.0  0.466708  0.443664  ...  0.0  0.0  0.0  1.0  0.0  1.0
2069  0.0  0.0  0.0  0.0  0.466708  0.443664  ...  0.0  0.0  0.0  1.0  0.0  1.0

[2070 rows x 1000 columns]


In [86]:
#Construct a Random Forest Classifier on text data
clf=RandomForestClassifier()
RF_text = clf.fit(DF_TF_IDF_SelectedFeatures,y_train)
print("Accuracy score (training): {0:.6f}".format(clf.score(DF_TF_IDF_SelectedFeatures, y_train)))
rf_predictions = clf.predict(DF_TF_IDF_SelectedFeatures)
print("Confusion Matrix:")
print(confusion_matrix(y_train, rf_predictions))
print("Classification Report")
print(classification_report(y_train, rf_predictions))

Accuracy score (training): 0.950725
Confusion Matrix:
[[ 757   47]
 [  55 1211]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.93      0.94      0.94       804
     Current       0.96      0.96      0.96      1266

    accuracy                           0.95      2070
   macro avg       0.95      0.95      0.95      2070
weighted avg       0.95      0.95      0.95      2070



In [87]:
#Construct a Decision Tree Classifier on text data
clf=DecisionTreeClassifier()
RF_text = clf.fit(DF_TF_IDF_SelectedFeatures,y_train)
print("Accuracy score (training): {0:.6f}".format(clf.score(DF_TF_IDF_SelectedFeatures, y_train)))
rf_predictions = clf.predict(DF_TF_IDF_SelectedFeatures)
print("Confusion Matrix:")
print(confusion_matrix(y_train, rf_predictions))
print("Classification Report")
print(classification_report(y_train, rf_predictions))

Accuracy score (training): 0.956522
Confusion Matrix:
[[ 782   22]
 [  68 1198]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.92      0.97      0.95       804
     Current       0.98      0.95      0.96      1266

    accuracy                           0.96      2070
   macro avg       0.95      0.96      0.95      2070
weighted avg       0.96      0.96      0.96      2070



In [98]:
from mlxtend.feature_selection import SequentialFeatureSelector as sfs

#Construct a Random Forest Classifier on text data
clf=RandomForestClassifier()

# Build step forward feature selection
sfs1 = sfs(clf,
           k_features=3,
           forward=True,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=3)

RF_text = sfs1.fit(combined_data,y_train)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4136 out of 4136 | elapsed:  3.4min finished

[2019-12-14 00:50:49] Features: 1/3 -- score: 0.6806763285024156[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4135 out of 4135 | elapsed:  3.8min finished

[2019-12-14 00:54:34] Features: 2/3 -- score: 0.7410628019323672[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4134 out of 4134 | elapsed:  3.8min finished

[2019-12-14 00:58:21] Features: 3/3 -- score: 0.7922705314009661

In [99]:
#Construct a Random Forest Classifier on text data
clf=RandomForestClassifier()

# Build step forward feature selection
sfs1 = sfs(clf,
           k_features=5,
           forward=True,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=5)

RF_text = sfs1.fit(combined_data,y_train)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4136 out of 4136 | elapsed:  5.5min finished

[2019-12-14 01:03:51] Features: 1/5 -- score: 0.6821003577773916[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4135 out of 4135 | elapsed:  6.1min finished

[2019-12-14 01:09:57] Features: 2/5 -- score: 0.7434567155874788[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.1s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4134 out of 4134 | elapsed:  6.0min finished

[2019-12-14 01:15:55] Features: 3/5 -- score: 0.7951499833773809[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Don

In [100]:
#Construct a Decision Tree Classifier on text data
clf=DecisionTreeClassifier()

# Build step forward feature selection
sfs1 = sfs(clf,
           k_features=3,
           forward=True,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=3)

RF_text = sfs1.fit(combined_data,y_train)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4136 out of 4136 | elapsed:   49.5s finished

[2019-12-14 01:29:12] Features: 1/3 -- score: 0.6801932367149758[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4135 out of 4135 | elapsed:   53.2s finished

[2019-12-14 01:30:06] Features: 2/3 -- score: 0.7425120772946859[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4134 out of 4134 | elapsed:   53.8s finished

[2019-12-14 01:31:00] Features: 3/3 -- score: 0.7903381642512078

In [101]:
#Construct a Decision Tree Classifier on text data
clf=DecisionTreeClassifier()
# Build step forward feature selection
sfs1 = sfs(clf,
           k_features=5,
           forward=True,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=5)
RF_text = sfs1.fit(combined_data,y_train)

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4136 out of 4136 | elapsed:  1.2min finished

[2019-12-14 01:32:13] Features: 1/5 -- score: 0.6830688751426381[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4135 out of 4135 | elapsed:  1.3min finished

[2019-12-14 01:33:33] Features: 2/5 -- score: 0.7429736238000393[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4134 out of 4134 | elapsed:  1.4min finished

[2019-12-14 01:34:55] Features: 3/5 -- score: 0.7932187803042187[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Don

In [102]:
#split the entire training data in training and test data
from sklearn.model_selection import train_test_split
X_Train, X_Test, Y_Train, Y_Test = train_test_split( combined_data, y_train, test_size=0.20, random_state=42)
print("Initial shape for entire data:",combined_data.shape)
print("Shape of new training data:", X_Train.shape)
print("Shape of new test split data:", X_Test.shape)

Initial shape for entire data: (2070, 4136)
Shape of new training data: (1656, 4136)
Shape of new test split data: (414, 4136)


In [103]:
#Feature selection Filter
new_DF_TF_IDF10 = SelectKBest(score_func=chi2, k=1000).fit(X_Train,Y_Train)
new_DF_TF_IDF = pd.DataFrame(new_DF_TF_IDF10.transform(X_Train))

DF_TF_IDF_SelectedFeatures= pd.DataFrame(new_DF_TF_IDF)


DF_TF_IDF_SelectedFeatures2 = pd.DataFrame(new_DF_TF_IDF10.transform(X_Test))

print(DF_TF_IDF_SelectedFeatures2)


          0    1         2    3         4    ...  995  996  997  998  999
0    0.368149  0.0  0.334347  0.0  0.000000  ...  0.0  0.0  1.0  1.0  0.0
1    0.000000  0.0  0.000000  0.0  0.000000  ...  0.0  0.0  1.0  0.0  1.0
2    0.000000  0.0  0.000000  0.0  0.000000  ...  0.0  0.0  0.0  0.0  1.0
3    0.000000  0.0  0.000000  0.0  0.000000  ...  0.0  0.0  0.0  0.0  1.0
4    0.000000  0.0  0.000000  0.0  0.000000  ...  0.0  0.0  1.0  0.0  1.0
..        ...  ...       ...  ...       ...  ...  ...  ...  ...  ...  ...
409  0.368149  0.0  0.334347  0.0  0.000000  ...  0.0  0.0  1.0  0.0  1.0
410  0.000000  0.0  0.000000  0.0  0.000000  ...  0.0  0.0  0.0  0.0  1.0
411  0.000000  0.0  0.000000  0.0  0.000000  ...  0.0  0.0  0.0  0.0  1.0
412  0.000000  0.0  0.000000  0.0  0.000000  ...  0.0  0.0  1.0  1.0  0.0
413  0.000000  0.0  0.000000  0.0  0.466708  ...  0.0  1.0  0.0  0.0  1.0

[414 rows x 1000 columns]


In [105]:
#Construct a Decision Tree Classifier on text data
clf=DecisionTreeClassifier()
RF_text = clf.fit(DF_TF_IDF_SelectedFeatures,Y_Train)
print("Accuracy score (training): {0:.6f}".format(clf.score(DF_TF_IDF_SelectedFeatures, Y_Train)))
rf_predictions = clf.predict(DF_TF_IDF_SelectedFeatures2)
print("Confusion Matrix:")
print(confusion_matrix(Y_Test, rf_predictions))
print("Classification Report")
print(classification_report(Y_Test, rf_predictions))

Accuracy score (training): 0.963164
Confusion Matrix:
[[126  31]
 [ 32 225]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.80      0.80      0.80       157
     Current       0.88      0.88      0.88       257

    accuracy                           0.85       414
   macro avg       0.84      0.84      0.84       414
weighted avg       0.85      0.85      0.85       414



In [108]:
#Construct a Decision Tree Classifier on text data
clf=DecisionTreeClassifier()

# Build step forward feature selection
sfs10 = sfs(clf,
           k_features=5,
           forward=True,
           floating=False,
           verbose=2,
           scoring='accuracy',
           cv=5)

RF_text = sfs10.fit(X_Train,Y_Train)


[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4136 out of 4136 | elapsed:  1.1min finished

[2019-12-14 02:11:33] Features: 1/5 -- score: 0.6745010142189191[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4135 out of 4135 | elapsed:  1.2min finished

[2019-12-14 02:12:44] Features: 2/5 -- score: 0.7391009795843633[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s
[Parallel(n_jobs=1)]: Done 4134 out of 4134 | elapsed:  1.2min finished

[2019-12-14 02:13:54] Features: 3/5 -- score: 0.7831734959613239[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Don

In [110]:
#selected features
selected_features = list(sfs10.k_feature_names_)
print(selected_features)

[199, 335, 'Sex_F', 'Children_2', 'Paymethod_Auto']


In [111]:

RF_text = clf.fit(X_Train[selected_features],Y_Train)
print("Accuracy score (training): {0:.6f}".format(clf.score(X_Train[selected_features], Y_Train)))
rf_predictions = clf.predict(X_Test[selected_features])
print("Confusion Matrix:")
print(confusion_matrix(Y_Test, rf_predictions))
print("Classification Report")
print(classification_report(Y_Test, rf_predictions))

Accuracy score (training): 0.846618
Confusion Matrix:
[[120  37]
 [ 32 225]]
Classification Report
              precision    recall  f1-score   support

   Cancelled       0.79      0.76      0.78       157
     Current       0.86      0.88      0.87       257

    accuracy                           0.83       414
   macro avg       0.82      0.82      0.82       414
weighted avg       0.83      0.83      0.83       414

